=== Jean1475/Lenguaje-de-Marcas/trabajo_xml_Gómez Giraldo,  El Yamani Serroukh_Jean Pierre, Omar/esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="habitaciones">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="habitacion" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="nombre_huesped" type="xs:string"/>
              <xs:element name="apellidos_huesped" type="xs:string" minOccurs="0"/>
              <xs:element name="edad" type="xs:integer"/>
              <xs:element name="fecha_entrada" type="xs:date" minOccurs="0"/>
              <xs:element name="fecha_salida" type="xs:date" minOccurs="0"/>
              <xs:element name="dni" type="xs:string"/>
              <xs:element name="nacionalidad" type="xs:string" minOccurs="0"/>

            </xs:sequence>

            <xs:attribute name="id" type="xs:integer" use="required"/>

          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Jean1475/Lenguaje-de-Marcas/trabajo_xml_Gómez Giraldo,  El Yamani Serroukh_Jean Pierre, Omar/datos.xml
<?xml version="1.0" encoding="UTF-8"?>

<habitaciones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="esquema.xsd">

    <habitacion id="1">
        <nombre_huesped>Jean Pierre</nombre_huesped>
        <apellidos_huesped>Gómez Giraldo</apellidos_huesped>
        <edad>25</edad>
        <fecha_entrada>2025-03-10</fecha_entrada>
        <fecha_salida>2025-03-15</fecha_salida>
        <dni>53890909D</dni>
        <nacionalidad>Colombiana</nacionalidad>
    </habitacion>

    <habitacion id="2">
        <nombre_huesped>Laura</nombre_huesped>
        <apellidos_huesped>Martínez Ríos</apellidos_huesped>
        <edad>32</edad>
        <fecha_entrada>2025-03-12</fecha_entrada>
        <fecha_salida>2025-03-18</fecha_salida>
        <dni>72451638K</dni>
        <nacionalidad>Española</nacionalidad>
    </habitacion>

    <habitacion id="3">
        <nombre_huesped>Carlos Andrés</nombre_huesped>
        <apellidos_huesped>Pineda López</apellidos_huesped>
        <edad>41</edad>
        <fecha_entrada>2025-03-08</fecha_entrada>
        <fecha_salida>2025-03-14</fecha_salida>
        <dni>18943752M</dni>
        <nacionalidad>Mexicana</nacionalidad>
    </habitacion>

    <habitacion id="4">
        <nombre_huesped>Sofía Elena</nombre_huesped>
        <apellidos_huesped>Navarro Torres</apellidos_huesped>
        <edad>28</edad>
        <fecha_entrada>2025-03-20</fecha_entrada>
        <fecha_salida>2025-03-25</fecha_salida>
        <dni>90628471R</dni>
        <nacionalidad>Argentina</nacionalidad>
    </habitacion>

</habitaciones>
